# windows/git-version.ps1
# Called from MSBuild PreBuildEvent to regenerate git_hash.h in the repo root.
# Usage: powershell -ExecutionPolicy Bypass -File git-version.ps1 [repo-root-path]
#
# Mirrors the logic of the bash GIT-VERSION-GEN script so Windows/MSVC builds
# get the same branch-aware version string as Linux autotools builds.

param([string]$RepoRoot = "")

if ($RepoRoot -eq "") {
    # Default: parent of the directory containing this script (= repo root)
    $RepoRoot = Split-Path $PSScriptRoot
}

# Resolve any ..\.. in the path so git -C gets a clean absolute path
$RepoRoot = [System.IO.Path]::GetFullPath($RepoRoot)

$versionFile = Join-Path $RepoRoot "VERSION"
$outFile     = Join-Path $RepoRoot "git_hash.h"

# Read base version from VERSION file
$baseVer = "2.5.1"
if (Test-Path $versionFile) {
    $baseVer = (Get-Content $versionFile -Raw).Trim()
}

try {
    $branch = ((git -C $RepoRoot branch --show-current 2>$null) -join "").Trim()
    $hash   = ((git -C $RepoRoot rev-parse --short HEAD  2>$null) -join "").Trim()
    $status = git -C $RepoRoot status --porcelain 2>$null
    $dirty  = ($status -ne $null -and $status.Length -gt 0)
    $now    = Get-Date -Format "yyyyMMdd.HHmmss"

    if ($branch -eq "main" -or $branch -eq "master") {
        $ver = $baseVer
    } elseif ($branch -match "^rc/(.+)$") {
        $ver = "$baseVer-rc$($Matches[1])"
    } elseif ($branch -eq "development") {
        $ver = "$baseVer-beta.$now"
    } elseif ($branch -match "^(feature|hotfix|bugfix)/") {
        $ver = "$baseVer-alpha.$now"
    } elseif ($hash -ne "") {
        $ver = "$baseVer-dev.$hash"
    } else {
        $ver = "$baseVer-unknown"
    }

    if ($dirty) { $ver = "$ver-modified" }
} catch {
    $ver = "$baseVer-unknown"
}

$content = @"
/* Auto-generated by windows/git-version.ps1 - do not edit manually. */
#ifndef GIT_HASH_H
#define GIT_HASH_H
#define GIT_VERSION    "$ver"
#endif /* GIT_HASH_H */
"@

# Only write if the version string changed (avoids triggering spurious recompiles)
$existing = ""
if (Test-Path $outFile) {
    $existing = Get-Content $outFile -Raw -ErrorAction SilentlyContinue
}

if (-not $existing -or $existing -notmatch [regex]::Escape($ver)) {
    # Write as ASCII (no BOM) to avoid MSVC byte-order-mark warnings
    [System.IO.File]::WriteAllText($outFile, $content, [System.Text.Encoding]::ASCII)
    Write-Host "git-version.ps1: GIT_VERSION = $ver  (updated $outFile)"
} else {
    Write-Host "git-version.ps1: GIT_VERSION = $ver  (unchanged)"
}

exit 0
