; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Mcaster1DNAS
AppVerName=Mcaster1DNAS v2.5.0
AppPublisherURL=https://www.mcaster1.com
AppSupportURL=https://www.mcaster1.com
AppUpdatesURL=https://www.mcaster1.com
DefaultDirName={pf}\Mcaster1DNAS
DefaultGroupName=Mcaster1DNAS
AllowNoIcons=yes
LicenseFile=..\LICENSE
InfoAfterFile=..\README
OutputDir=.
OutputBaseFilename=mcaster1dnas_win32_v2.5.0_setup
WizardImageFile=mcaster1dnaslogo2.bmp
WizardImageStretch=no
VersionInfoVersion=2.5.0
; uncomment the following line if you want your installation to run on NT 3.51 too.
; MinVersion=4,3.51

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; MinVersion: 4,4

[Dirs]
Name: "{app}\web"
Name: "{app}\admin"
Name: "{app}\doc"
Name: "{app}\logs"
Name: "{app}\examples"


[Files]
Source: "win_release\mcaster1win.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "console_release\mcaster1dnas_console.exe"; DestDir: "{app}"; DestName: "mcaster1dnas_console.exe"; Flags: ignoreversion
Source: "service_Release\mcaster1Service.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\examples\*"; DestDir: "{app}\examples"; Excludes: "*~"; Flags: ignoreversion
Source: "..\doc\*"; DestDir: "{app}\doc"; Excludes: "*Makefile*"; Flags: ignoreversion
Source: "..\web\*.xsl"; DestDir: "{app}\web"; Flags: ignoreversion
Source: "..\web\*.html"; DestDir: "{app}\web"; Flags: ignoreversion
Source: "..\web\images\*.png"; DestDir: "{app}\web\images"; Flags: ignoreversion
Source: "..\web\images\*.jpg"; DestDir: "{app}\web\images"; Flags: ignoreversion
Source: "..\web\*.css"; DestDir: "{app}\web"; Flags: ignoreversion
Source: "..\admin\*.xsl"; DestDir: "{app}\admin"; Flags: ignoreversion
Source: "..\admin\flashpolicy"; DestDir: "{app}\admin"; Flags: ignoreversion
Source: "..\conf\*.dist"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\examples\mcaster1_shoutcast_compat.xml"; DestDir: "{app}"; DestName: "mcaster1.xml"; Flags: ignoreversion confirmoverwrite
Source: ".\pthreadVSE.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\iconv.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\ogg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\libspeex.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\libxslt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\libxml2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\libcurl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\libeay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\ssleay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion

[Icons]

Name: "{group}\Mcaster1DNAS"; Filename: "{app}\mcaster1win.exe";WorkingDir: "{app}";
Name: "{userdesktop}\Mcaster1DNAS"; Filename: "{app}\mcaster1win.exe"; MinVersion: 4,4; Tasks: desktopicon;WorkingDir: "{app}";

[Run]
Filename: "{app}\mcaster1Service.exe"; Parameters: "install ""{app}""";Description: "Install Mcaster1DNAS as a windows service.";Flags: postinstall

[UninstallRun]
Filename: "{app}\mcaster1Service.exe"; Parameters: "remove"

